opt_in_rules:
  - legacy_random
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - force_cast
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - large_tuple
  - file_length
